// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ-u9yowt-TGzXjLhbAT5KhTdoQJ5pnww',
    appId: '1:600875346397:web:8edfd2dbd0dcdca6d4ee34',
    messagingSenderId: '600875346397',
    projectId: 'fusionfiesta-b5545',
    authDomain: 'fusionfiesta-b5545.firebaseapp.com',
    storageBucket: 'fusionfiesta-b5545.firebasestorage.app',
    measurementId: 'G-P7MDLN9V4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrKY5E8SDfuZo4nxPnGXYNDLhGKr952GA',
    appId: '1:600875346397:android:8fa76afe99eaafc1d4ee34',
    messagingSenderId: '600875346397',
    projectId: 'fusionfiesta-b5545',
    storageBucket: 'fusionfiesta-b5545.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDToZzLG1ygjiV2MtyIkPXcHUt6qKhq-jM',
    appId: '1:600875346397:ios:c064cce960a04aded4ee34',
    messagingSenderId: '600875346397',
    projectId: 'fusionfiesta-b5545',
    storageBucket: 'fusionfiesta-b5545.firebasestorage.app',
    androidClientId: '600875346397-bbk50lii6us92bd98pipi1fbidcm34fa.apps.googleusercontent.com',
    iosClientId: '600875346397-6lo6a2j3a51rtfmoork5jdjeo2q6t6k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fusionFiesta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDToZzLG1ygjiV2MtyIkPXcHUt6qKhq-jM',
    appId: '1:600875346397:ios:c064cce960a04aded4ee34',
    messagingSenderId: '600875346397',
    projectId: 'fusionfiesta-b5545',
    storageBucket: 'fusionfiesta-b5545.firebasestorage.app',
    androidClientId: '600875346397-bbk50lii6us92bd98pipi1fbidcm34fa.apps.googleusercontent.com',
    iosClientId: '600875346397-6lo6a2j3a51rtfmoork5jdjeo2q6t6k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fusionFiesta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ-u9yowt-TGzXjLhbAT5KhTdoQJ5pnww',
    appId: '1:600875346397:web:6ed6e4380894f877d4ee34',
    messagingSenderId: '600875346397',
    projectId: 'fusionfiesta-b5545',
    authDomain: 'fusionfiesta-b5545.firebaseapp.com',
    storageBucket: 'fusionfiesta-b5545.firebasestorage.app',
    measurementId: 'G-W21WQE2Z6L',
  );
}
